cluster:
  mkdir -p build/logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={resources.cpus}
    --mem={resources.mem_mb}
    --job-name={rule}
    --time={resources.time}
    --parsable
    --output=build/logs/%j.out
    --error=build/logs/%j.err
resources:
    - cpus=60
default-resources:
  - partition=short
  - time=120
  - mem_mb=8000
  - cpus=1
# restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 1 # 60
jobs: 100  # maximum number of simultaneously submitted jobs
# keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
cluster-cancel: scancel
cluster-status: status-sacct.sh
